[tool.poetry]
name = "ai-department"
version = "0.1.0"
description = "The backend of AI Department web application"
authors = ["Farrukh Yuldoshev <codingmaestro.uz@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastapi = "^0.115.7"
alembic = {extras = ["async"], version = "^1.14.1"}
uvicorn = {extras = ["standart"], version = "^0.34.0"}
pydantic-settings = "^2.7.1"
pydantic = {extras = ["email"], version = "^2.10.6"}
black = "^24.10.0"
asyncpg = "^0.30.0"
aiofiles = "^24.1.0"
python-multipart = "^0.0.20"
ipython = "^8.31.0"
pyjwt = {extras = ["crypto"], version = "^2.10.1"}
bcrypt = "^4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
