"""removed views field from Announcements

Revision ID: 88e47a67ad1f
Revises: af4740c3e453
Create Date: 2025-02-20 16:01:45.411575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88e47a67ad1f"
down_revision: Union[str, None] = "af4740c3e453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "views")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("views", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
