"""empty message

Revision ID: 06e3c2e2a698
Revises: 88e47a67ad1f
Create Date: 2025-02-21 15:30:01.204542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06e3c2e2a698"
down_revision: Union[str, None] = "88e47a67ad1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.drop_column("announcements", "title")
    op.drop_column("announcements", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "announcements",
        sa.Column(
            "title",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("announcements", "translations")
    # ### end Alembic commands ###
