"""empty message

Revision ID: af4740c3e453
Revises: 
Create Date: 2025-02-19 15:41:23.754955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af4740c3e453"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "images", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "publications",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("pre_print_link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "research_interests",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "teachers",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "head_of_the_department",
                "professor",
                "associate_professor",
                "senior_lecturer",
                "teacher",
                "staff",
                name="roles",
            ),
            nullable=False,
        ),
        sa.Column("image", sa.String(length=100), nullable=True),
        sa.Column("scopus_link", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "education",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("place", sa.String(length=1024), nullable=False),
        sa.Column(
            "degree",
            sa.Enum("Bsc", "Dsc", "Phd", name="degrees"),
            nullable=False,
        ),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "place",
            "teacher_id",
            "degree",
            name="educations_title_teacher_id_uidx",
        ),
    )
    op.create_table(
        "publications_teachers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["publications.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_id", "teacher_id"),
    )
    op.create_table(
        "research_interests_teachers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("research_interests_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_interests_id"],
            ["research_interests.uuid"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "research_interests_id",
            "teacher_id",
            name="research_interests_teacher_unx",
        ),
    )
    op.create_table(
        "work_experience",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("place", sa.String(length=1024), nullable=False),
        sa.Column("role", sa.String(length=256), nullable=True),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "place",
            "role",
            "teacher_id",
            name="work_experience_title_teacher_id_uidx",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_experience")
    op.drop_table("research_interests_teachers")
    op.drop_table("publications_teachers")
    op.drop_table("education")
    op.drop_table("teachers")
    op.drop_table("research_interests")
    op.drop_table("publications")
    op.drop_table("announcements")
    # ### end Alembic commands ###
