"""empty message

Revision ID: a348544ae539
Revises: 952cb4973012
Create Date: 2025-03-06 02:48:25.190628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a348544ae539"
down_revision: Union[str, None] = "952cb4973012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_programs",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("year_of_study", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "subjects",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("academic_program_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_program_id"],
            ["academic_programs.uuid"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uniq_research_interests_titles",
        "research_interests",
        [
            sa.text("((translations -> 'uz'::text) ->> 'title'::text)"),
            sa.text("((translations -> 'ru'::text) ->> 'title'::text)"),
            sa.text("((translations -> 'en'::text) ->> 'title'::text)"),
        ],
        unique=True,
    )
    op.drop_table("subjects")
    op.drop_table("academic_programs")
    # ### end Alembic commands ###
